title: Site
pages:
  template:
    - default
fields:
  generalSettings:
    label: Site Settings
    type: headline
  title:
    label: Title
    type:  text
  description:
    label: Description
    type:  textarea
  keywords:
    label: Keywords
    type:  tags
  customcss:
    label: Custom CSS
    type: textarea
    buttons: false
  googleAnalytics:
    label: Google Analytics ID
    type: text
    icon: code
    help: Tracking ID in the form UA-XXXXXXXX-X. Keep this field empty if you are not using it.
    width: 1/2
  ogimage:
    label: Facebook OpenGraph image
    type: image
    help: 1200x630px minimum
    width: 1/2
  shopRocketShopID:
    label: Shoprocket Shop ID
    type: text
    icon: code
  menu:
    label: Menu
    type: structure
    style: table
    width: 1/2
    fields:
      page:
        label: Page
        type: quickselect
        options: pages
        required: true
  socials:
    label: Socials
    type: structure
    style: table
    width: 1/2
    fields:
      title:
        label: Title
        type: text
        required: true
      url:
        label: URL
        type: url
        required: true
  board:
    label: Menu board
    type: structure
    style: table
    fields:
      title:
        label: Title
        type: text
      text:
        label: Text
        type: textarea
      author:
        label: Author
        type: text
      image:
        label: Image
        type: image